parameters:
  - name: shouldPublish # name of the parameter; required
    type: boolean # data type of the parameter; required

steps:
  - script: node common/scripts/install-run-rush.js publish --publish -a -b main --set-access-level public
    displayName: rush publish package
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranch'], 'refs/heads/main'), ${{ parameters.shouldPublish }} )
    env:
      NPM_AUTH_TOKEN: $(npmToken)
# this is going to have to be altered to do the next-version dance for an out of step repo
